spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 123qweasdzxc
    driver-class-name: com.mysql.jdbc.Driver